# PBS configuration
# If submitting to a different project to your default uncomment line below 
# and change project code as appropriate
# project: w35

walltime: 3:00:00
jobname: 1deg_jra55_iaf
ncpus: 252
mem: 500GB
queue: normalbw

# Force payu to always find, and save, files in this short project 
# directory
# shortpath: /short/w35

# Model configuration
name: common
model: access-om2
input: /short/public/access-om2/input_236a3011/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/v45/aek156/sources/chuckable/access-om2-raijin/bin/yatm_13315f5.exe
      input: 
          - /short/public/access-om2/input_236a3011/yatm_1deg
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/rsds/gn/v20180412/rsds
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/rlds/gn/v20180412/rlds
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/prra/gn/v20180412/prra
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/prsn/gn/v20180412/prsn
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/psl/gn/v20180412/psl
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/ocean/day/friver/gn/v20180412/friver
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/tas/gn/v20180412/tas
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/huss/gn/v20180412/huss
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/uas/gn/v20180412/uas
          - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/vas/gn/v20180412/vas
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/v45/aek156/sources/chuckable/access-om2-raijin/bin/fms_ACCESS-OM_46774ee_libaccessom2_13315f5.x
      input: /short/public/access-om2/input_236a3011/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /short/v45/aek156/sources/chuckable/access-om2-raijin/bin/cice_auscom_360x300_24p_dd02b01_libaccessom2_13315f5.exe
      input: /short/public/access-om2/input_236a3011/cice_1deg
      ncpus: 24

# Misc
runlog: true
stacksize: unlimited
collate:
   exe: /short/public/access-om2/bin/mppnccombine
   walltime: 1:00:00
   queue: copyq
   mem: 4GB

qsub_flags: -lother=hyperthread -W umask=027
# Following two lines required for broadwell queues
platform:
    nodesize: 28

# DANGER! Do not uncomment this without checking the script is synching 
# to the correct location!
# postscript: sync_output_to_gdata.sh
